# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BennettYang.LittleAgents
PackageVersion: 0.1.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-07-11
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Bennett-Yang/LittleAgentsExtensionForCmdPal/releases/download/LittleAgentsExtension-v0.1.0/LittleAgentsExtension-Setup-0.1.0-x64.exe
  InstallerSha256: fa608a8a8c4c466ce8152a535f758fa499a9e32a302102811bd392ea3d8f7c20
- Architecture: arm64
  InstallerUrl: https://github.com/Bennett-Yang/LittleAgentsExtensionForCmdPal/releases/download/LittleAgentsExtension-v0.1.0/LittleAgentsExtension-Setup-0.1.0-arm64.exe
  InstallerSha256: c6e5f8859934b582d38eb7c8ed0de5617c29f9ba932d669ce916121e2edff7cc
ManifestType: installer
ManifestVersion: 1.12.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.WindowsAppRuntime.1.8