# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BennettYang.LittleAgents
PackageVersion: 0.1.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-07-11
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Bennett-Yang/LittleAgentsExtensionForCmdPal/releases/download/LittleAgentsExtension-v0.1.0/LittleAgentsExtension-Setup-0.1.0-x64.exe
  InstallerSha256: 39a5746b02a89baa44c75cfb3fd8bfb64083844471f6ed14292d79080b105018
- Architecture: arm64
  InstallerUrl: https://github.com/Bennett-Yang/LittleAgentsExtensionForCmdPal/releases/download/LittleAgentsExtension-v0.1.0/LittleAgentsExtension-Setup-0.1.0-arm64.exe
  InstallerSha256: a875bb1aca971abfc2134d956b920aa3d962da6be1150304924e66bde7c62ea9
ManifestType: installer
ManifestVersion: 1.12.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.WindowsAppRuntime.1.8